// Package rizalsclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package rizalsclient

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BarbershopsAppBusinessKind.
const (
	Company    BarbershopsAppBusinessKind = "company"
	Individual BarbershopsAppBusinessKind = "individual"
)

// ApiError defines model for ApiError.
type ApiError struct {
	Code   int64  `json:"code"`
	Detail string `json:"detail"`
	Title  string `json:"title"`
}

// AuthServiceForgotPasswordInput defines model for AuthServiceForgotPasswordInput.
type AuthServiceForgotPasswordInput struct {
	Email string `json:"email"`
}

// AuthServiceResetPasswordInput defines model for AuthServiceResetPasswordInput.
type AuthServiceResetPasswordInput struct {
	Email       string  `json:"email"`
	NewPassword string  `json:"newPassword"`
	OldPassword *string `json:"oldPassword,omitempty"`
	Token       *string `json:"token,omitempty"`
}

// AuthServiceSignInInput defines model for AuthServiceSignInInput.
type AuthServiceSignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// AuthServiceSignUpInput defines model for AuthServiceSignUpInput.
type AuthServiceSignUpInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

// AuthServiceUpdateUserInput defines model for AuthServiceUpdateUserInput.
type AuthServiceUpdateUserInput struct {
	Name     *string             `json:"name,omitempty"`
	Phone    *string             `json:"phone,omitempty"`
	Photo    *openapi_types.File `json:"photo,omitempty"`
	Username *string             `json:"username,omitempty"`
}

// AuthServiceUser defines model for AuthServiceUser.
type AuthServiceUser struct {
	Email         string             `json:"email"`
	EmailVerified bool               `json:"emailVerified"`
	Id            openapi_types.UUID `json:"id"`
	IsAdmin       bool               `json:"isAdmin"`
	Name          string             `json:"name"`
	Phone         string             `json:"phone"`
	PhoneVerified bool               `json:"phoneVerified"`
	PhotoUrl      *string            `json:"photoUrl,omitempty"`
}

// AuthServiceVerifyEmailInput defines model for AuthServiceVerifyEmailInput.
type AuthServiceVerifyEmailInput struct {
	Token string `json:"token"`
}

// AuthServiceVerifyPhoneInput defines model for AuthServiceVerifyPhoneInput.
type AuthServiceVerifyPhoneInput struct {
	Code string `json:"code"`
}

// BarbershopsAppBooking defines model for BarbershopsAppBooking.
type BarbershopsAppBooking struct {
	BusinessId          openapi_types.UUID `json:"businessId"`
	BusinessMemberId    openapi_types.UUID `json:"businessMemberId"`
	BusinessMemberName  string             `json:"businessMemberName"`
	BusinessMemberPhoto *string            `json:"businessMemberPhoto,omitempty"`
	BusinessName        string             `json:"businessName"`
	CancelledAt         *time.Time         `json:"cancelledAt,omitempty"`
	ConfirmedAt         *time.Time         `json:"confirmedAt,omitempty"`
	CreatedAt           time.Time          `json:"createdAt"`
	Currency            string             `json:"currency"`
	Id                  openapi_types.UUID `json:"id"`
	PaidAt              *time.Time         `json:"paidAt,omitempty"`
	Price               float64            `json:"price"`
	PriceInUnit         int64              `json:"priceInUnit"`
	RejectedAt          *time.Time         `json:"rejectedAt,omitempty"`
	ServiceDescription  string             `json:"serviceDescription"`
	ServiceDuration     int64              `json:"serviceDuration"`
	ServiceName         string             `json:"serviceName"`
	ServicePhoto        *string            `json:"servicePhoto,omitempty"`
	ServiceTypeId       openapi_types.UUID `json:"serviceTypeId"`
	Time                time.Time          `json:"time"`
	UserEmail           string             `json:"userEmail"`
	UserId              openapi_types.UUID `json:"userId"`
	UserName            string             `json:"userName"`
	UserPhone           string             `json:"userPhone"`
	UserPhoto           *string            `json:"userPhoto,omitempty"`
}

// BarbershopsAppBookingInput defines model for BarbershopsAppBookingInput.
type BarbershopsAppBookingInput struct {
	BusinessMemberId *openapi_types.UUID `json:"businessMemberId,omitempty"`
	PaymentIntentId  *string             `json:"paymentIntentId,omitempty"`
	ServiceTypeId    openapi_types.UUID  `json:"serviceTypeId"`
	Time             time.Time           `json:"time"`
}

// BarbershopsAppBusiness defines model for BarbershopsAppBusiness.
type BarbershopsAppBusiness struct {
	Address1         string                     `json:"address1"`
	Address2         *string                    `json:"address2,omitempty"`
	City             string                     `json:"city"`
	Country          string                     `json:"country"`
	Currency         string                     `json:"currency"`
	Description      *string                    `json:"description,omitempty"`
	DistanceInMeters *float64                   `json:"distanceInMeters,omitempty"`
	Email            string                     `json:"email"`
	HomeService      bool                       `json:"homeService"`
	Id               openapi_types.UUID         `json:"id"`
	Kind             BarbershopsAppBusinessKind `json:"kind"`
	Lat              float64                    `json:"lat"`
	Lng              float64                    `json:"lng"`
	LogoUrl          *string                    `json:"logoUrl,omitempty"`
	MinPrice         float64                    `json:"minPrice"`
	MinPriceInUnit   int64                      `json:"minPriceInUnit"`
	Name             string                     `json:"name"`
	Phone            string                     `json:"phone"`
	PhotoUrl         *string                    `json:"photoUrl,omitempty"`
	PostalCode       string                     `json:"postalCode"`
	Rating           *float64                   `json:"rating,omitempty"`
	Region           string                     `json:"region"`
	Website          string                     `json:"website"`
}

// BarbershopsAppBusinessKind defines model for BarbershopsAppBusiness.Kind.
type BarbershopsAppBusinessKind string

// BarbershopsAppBusinessBalance defines model for BarbershopsAppBusinessBalance.
type BarbershopsAppBusinessBalance struct {
	Available        float64                                    `json:"available"`
	AvailableInUnits int64                                      `json:"availableInUnits"`
	Pending          float64                                    `json:"pending"`
	PendingInUnits   int64                                      `json:"pendingInUnits"`
	Transactions     []BarbershopsAppBusinessBalanceTransaction `json:"transactions"`
}

// BarbershopsAppBusinessBalanceTransaction defines model for BarbershopsAppBusinessBalanceTransaction.
type BarbershopsAppBusinessBalanceTransaction struct {
	Amount            int64                      `json:"amount"`
	AvailableOn       int64                      `json:"availableOn"`
	Created           int64                      `json:"created"`
	Currency          string                     `json:"currency"`
	Description       *string                    `json:"description,omitempty"`
	ExchangeRate      *string                    `json:"exchangeRate,omitempty"`
	Fee               int64                      `json:"fee"`
	FeeDetails        *[]BarbershopsAppFeeDetail `json:"feeDetails,omitempty"`
	Id                string                     `json:"id"`
	Net               int64                      `json:"net"`
	Object            string                     `json:"object"`
	ReportingCategory string                     `json:"reportingCategory"`
	Source            string                     `json:"source"`
	Status            string                     `json:"status"`
	Type              string                     `json:"type"`
}

// BarbershopsAppBusinessMember defines model for BarbershopsAppBusinessMember.
type BarbershopsAppBusinessMember struct {
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	PhotoUrl    *string            `json:"photoUrl,omitempty"`
}

// BarbershopsAppBusinessPhoto defines model for BarbershopsAppBusinessPhoto.
type BarbershopsAppBusinessPhoto struct {
	Alt        string             `json:"alt"`
	Id         openapi_types.UUID `json:"id"`
	IsCarousel bool               `json:"isCarousel"`
	PhotoUrl   *string            `json:"photoUrl,omitempty"`
	Sort       float64            `json:"sort"`
}

// BarbershopsAppBusinessRequirements defines model for BarbershopsAppBusinessRequirements.
type BarbershopsAppBusinessRequirements struct {
	AccountIsDisabled                       bool    `json:"accountIsDisabled"`
	AreThereMissingRequirements             bool    `json:"areThereMissingRequirements"`
	AreThereRequirementsPendingVerification bool    `json:"areThereRequirementsPendingVerification"`
	CompleteRequirementsLink                *string `json:"completeRequirementsLink,omitempty"`
}

// BarbershopsAppBusinessSchedule defines model for BarbershopsAppBusinessSchedule.
type BarbershopsAppBusinessSchedule struct {
	FriBreakEnd   *BarbershopsAppOnlyTime `json:"friBreakEnd,omitempty"`
	FriBreakStart *BarbershopsAppOnlyTime `json:"friBreakStart,omitempty"`
	FriClose      *BarbershopsAppOnlyTime `json:"friClose,omitempty"`
	FriOpen       *BarbershopsAppOnlyTime `json:"friOpen,omitempty"`
	MonBreakEnd   *BarbershopsAppOnlyTime `json:"monBreakEnd,omitempty"`
	MonBreakStart *BarbershopsAppOnlyTime `json:"monBreakStart,omitempty"`
	MonClose      *BarbershopsAppOnlyTime `json:"monClose,omitempty"`
	MonOpen       *BarbershopsAppOnlyTime `json:"monOpen,omitempty"`
	SatBreakEnd   *BarbershopsAppOnlyTime `json:"satBreakEnd,omitempty"`
	SatBreakStart *BarbershopsAppOnlyTime `json:"satBreakStart,omitempty"`
	SatClose      *BarbershopsAppOnlyTime `json:"satClose,omitempty"`
	SatOpen       *BarbershopsAppOnlyTime `json:"satOpen,omitempty"`
	SunBreakEnd   *BarbershopsAppOnlyTime `json:"sunBreakEnd,omitempty"`
	SunBreakStart *BarbershopsAppOnlyTime `json:"sunBreakStart,omitempty"`
	SunClose      *BarbershopsAppOnlyTime `json:"sunClose,omitempty"`
	SunOpen       *BarbershopsAppOnlyTime `json:"sunOpen,omitempty"`
	ThuBreakEnd   *BarbershopsAppOnlyTime `json:"thuBreakEnd,omitempty"`
	ThuBreakStart *BarbershopsAppOnlyTime `json:"thuBreakStart,omitempty"`
	ThuClose      *BarbershopsAppOnlyTime `json:"thuClose,omitempty"`
	ThuOpen       *BarbershopsAppOnlyTime `json:"thuOpen,omitempty"`
	TueBreakEnd   *BarbershopsAppOnlyTime `json:"tueBreakEnd,omitempty"`
	TueBreakStart *BarbershopsAppOnlyTime `json:"tueBreakStart,omitempty"`
	TueClose      *BarbershopsAppOnlyTime `json:"tueClose,omitempty"`
	TueOpen       *BarbershopsAppOnlyTime `json:"tueOpen,omitempty"`
	WedBreakEnd   *BarbershopsAppOnlyTime `json:"wedBreakEnd,omitempty"`
	WedBreakStart *BarbershopsAppOnlyTime `json:"wedBreakStart,omitempty"`
	WedClose      *BarbershopsAppOnlyTime `json:"wedClose,omitempty"`
	WedOpen       *BarbershopsAppOnlyTime `json:"wedOpen,omitempty"`
}

// BarbershopsAppBusinessScheduleInput defines model for BarbershopsAppBusinessScheduleInput.
type BarbershopsAppBusinessScheduleInput struct {
	FriBreakEnd   *BarbershopsAppOnlyTime `json:"friBreakEnd,omitempty"`
	FriBreakStart *BarbershopsAppOnlyTime `json:"friBreakStart,omitempty"`
	FriClose      *BarbershopsAppOnlyTime `json:"friClose,omitempty"`
	FriOpen       *BarbershopsAppOnlyTime `json:"friOpen,omitempty"`
	MonBreakEnd   *BarbershopsAppOnlyTime `json:"monBreakEnd,omitempty"`
	MonBreakStart *BarbershopsAppOnlyTime `json:"monBreakStart,omitempty"`
	MonClose      *BarbershopsAppOnlyTime `json:"monClose,omitempty"`
	MonOpen       *BarbershopsAppOnlyTime `json:"monOpen,omitempty"`
	SatBreakEnd   *BarbershopsAppOnlyTime `json:"satBreakEnd,omitempty"`
	SatBreakStart *BarbershopsAppOnlyTime `json:"satBreakStart,omitempty"`
	SatClose      *BarbershopsAppOnlyTime `json:"satClose,omitempty"`
	SatOpen       *BarbershopsAppOnlyTime `json:"satOpen,omitempty"`
	SunBreakEnd   *BarbershopsAppOnlyTime `json:"sunBreakEnd,omitempty"`
	SunBreakStart *BarbershopsAppOnlyTime `json:"sunBreakStart,omitempty"`
	SunClose      *BarbershopsAppOnlyTime `json:"sunClose,omitempty"`
	SunOpen       *BarbershopsAppOnlyTime `json:"sunOpen,omitempty"`
	ThuBreakEnd   *BarbershopsAppOnlyTime `json:"thuBreakEnd,omitempty"`
	ThuBreakStart *BarbershopsAppOnlyTime `json:"thuBreakStart,omitempty"`
	ThuClose      *BarbershopsAppOnlyTime `json:"thuClose,omitempty"`
	ThuOpen       *BarbershopsAppOnlyTime `json:"thuOpen,omitempty"`
	TueBreakEnd   *BarbershopsAppOnlyTime `json:"tueBreakEnd,omitempty"`
	TueBreakStart *BarbershopsAppOnlyTime `json:"tueBreakStart,omitempty"`
	TueClose      *BarbershopsAppOnlyTime `json:"tueClose,omitempty"`
	TueOpen       *BarbershopsAppOnlyTime `json:"tueOpen,omitempty"`
	WedBreakEnd   *BarbershopsAppOnlyTime `json:"wedBreakEnd,omitempty"`
	WedBreakStart *BarbershopsAppOnlyTime `json:"wedBreakStart,omitempty"`
	WedClose      *BarbershopsAppOnlyTime `json:"wedClose,omitempty"`
	WedOpen       *BarbershopsAppOnlyTime `json:"wedOpen,omitempty"`
}

// BarbershopsAppBusinessSettings defines model for BarbershopsAppBusinessSettings.
type BarbershopsAppBusinessSettings struct {
	AcceptsBookings       bool  `json:"acceptsBookings"`
	AcceptsCashPayments   bool  `json:"acceptsCashPayments"`
	AcceptsOnlinePayments bool  `json:"acceptsOnlinePayments"`
	AutoConfirm           bool  `json:"autoConfirm"`
	SlotInterval          int64 `json:"slotInterval"`
}

// BarbershopsAppBusinessSettingsInput defines model for BarbershopsAppBusinessSettingsInput.
type BarbershopsAppBusinessSettingsInput struct {
	AcceptsBookings       bool  `json:"acceptsBookings"`
	AcceptsCashPayments   bool  `json:"acceptsCashPayments"`
	AcceptsOnlinePayments bool  `json:"acceptsOnlinePayments"`
	AutoConfirm           bool  `json:"autoConfirm"`
	SlotInterval          int64 `json:"slotInterval"`
}

// BarbershopsAppCountry defines model for BarbershopsAppCountry.
type BarbershopsAppCountry struct {
	Alpha2    string `json:"alpha2"`
	Alpha3    string `json:"alpha3"`
	Currency  string `json:"currency"`
	Emoji     string `json:"emoji"`
	Name      string `json:"name"`
	PhoneCode string `json:"phoneCode"`
}

// BarbershopsAppCountryInput defines model for BarbershopsAppCountryInput.
type BarbershopsAppCountryInput struct {
	Alpha2    string `json:"alpha2"`
	Alpha3    string `json:"alpha3"`
	Currency  string `json:"currency"`
	Emoji     string `json:"emoji"`
	Name      string `json:"name"`
	PhoneCode string `json:"phoneCode"`
}

// BarbershopsAppCreateBusinessInput defines model for BarbershopsAppCreateBusinessInput.
type BarbershopsAppCreateBusinessInput struct {
	Address1    *string             `json:"address1,omitempty"`
	Address2    *string             `json:"address2,omitempty"`
	City        *string             `json:"city,omitempty"`
	Country     string              `json:"country"`
	Description *string             `json:"description,omitempty"`
	Email       *string             `json:"email,omitempty"`
	HomeService *bool               `json:"homeService,omitempty"`
	Kind        string              `json:"kind"`
	Lat         *float64            `json:"lat,omitempty"`
	Lng         *float64            `json:"lng,omitempty"`
	Logo        *openapi_types.File `json:"logo,omitempty"`
	Name        string              `json:"name"`
	Phone       *string             `json:"phone,omitempty"`
	PostalCode  *string             `json:"postalCode,omitempty"`
	Region      *string             `json:"region,omitempty"`
	Website     *string             `json:"website,omitempty"`
}

// BarbershopsAppCreateBusinessMemberInput defines model for BarbershopsAppCreateBusinessMemberInput.
type BarbershopsAppCreateBusinessMemberInput struct {
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	Photo       *openapi_types.File `json:"photo,omitempty"`
}

// BarbershopsAppCreatePhotoInput defines model for BarbershopsAppCreatePhotoInput.
type BarbershopsAppCreatePhotoInput struct {
	Alt        *string             `json:"alt,omitempty"`
	Image      *openapi_types.File `json:"image,omitempty"`
	IsCarousel *bool               `json:"isCarousel,omitempty"`
}

// BarbershopsAppCreateServiceTypeInput defines model for BarbershopsAppCreateServiceTypeInput.
type BarbershopsAppCreateServiceTypeInput struct {
	Description *string             `json:"description,omitempty"`
	Duration    int64               `json:"duration"`
	Kind        *string             `json:"kind,omitempty"`
	Name        string              `json:"name"`
	Photo       *openapi_types.File `json:"photo,omitempty"`
	Price       float64             `json:"price"`
}

// BarbershopsAppCustomer defines model for BarbershopsAppCustomer.
type BarbershopsAppCustomer struct {
	Bookings   int64              `json:"bookings"`
	BusinessId openapi_types.UUID `json:"businessId"`
	Name       string             `json:"name"`
	Photo      *string            `json:"photo,omitempty"`
	UserId     openapi_types.UUID `json:"userId"`
}

// BarbershopsAppFeeDetail defines model for BarbershopsAppFeeDetail.
type BarbershopsAppFeeDetail struct {
	Description *string `json:"description,omitempty"`
}

// BarbershopsAppOnlyTime defines model for BarbershopsAppOnlyTime.
type BarbershopsAppOnlyTime struct {
	Hour   int64 `json:"hour"`
	Minute int64 `json:"minute"`
}

// BarbershopsAppPaymentIntent defines model for BarbershopsAppPaymentIntent.
type BarbershopsAppPaymentIntent struct {
	ClientSecret string `json:"clientSecret"`
	Id           string `json:"id"`
}

// BarbershopsAppPaymentIntentInput defines model for BarbershopsAppPaymentIntentInput.
type BarbershopsAppPaymentIntentInput struct {
	ServiceTypeId openapi_types.UUID `json:"serviceTypeId"`
	Time          time.Time          `json:"time"`
}

// BarbershopsAppPublicBusinessSettings defines model for BarbershopsAppPublicBusinessSettings.
type BarbershopsAppPublicBusinessSettings struct {
	AcceptsBookings       bool `json:"acceptsBookings"`
	AcceptsCashPayments   bool `json:"acceptsCashPayments"`
	AcceptsOnlinePayments bool `json:"acceptsOnlinePayments"`
	AutoConfirm           bool `json:"autoConfirm"`
}

// BarbershopsAppReview defines model for BarbershopsAppReview.
type BarbershopsAppReview struct {
	Comment   *string            `json:"comment,omitempty"`
	CreatedAt string             `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Rating    int64              `json:"rating"`
	Title     *string            `json:"title,omitempty"`
	UserName  string             `json:"userName"`
	UserPhoto *string            `json:"userPhoto,omitempty"`
}

// BarbershopsAppReviewInput defines model for BarbershopsAppReviewInput.
type BarbershopsAppReviewInput struct {
	Comment *string `json:"comment,omitempty"`
	Rating  int64   `json:"rating"`
	Title   *string `json:"title,omitempty"`
}

// BarbershopsAppServiceType defines model for BarbershopsAppServiceType.
type BarbershopsAppServiceType struct {
	Currency     string             `json:"currency"`
	Description  string             `json:"description"`
	Duration     int64              `json:"duration"`
	Id           openapi_types.UUID `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	PhotoUrl     *string            `json:"photoUrl,omitempty"`
	Price        float64            `json:"price"`
	PriceInUnits int64              `json:"priceInUnits"`
}

// BarbershopsAppSlot defines model for BarbershopsAppSlot.
type BarbershopsAppSlot struct {
	Available bool      `json:"available"`
	Time      time.Time `json:"time"`
}

// BarbershopsAppUpdateBusinessInput defines model for BarbershopsAppUpdateBusinessInput.
type BarbershopsAppUpdateBusinessInput struct {
	Address1    *string             `json:"address1,omitempty"`
	Address2    *string             `json:"address2,omitempty"`
	City        *string             `json:"city,omitempty"`
	Country     *string             `json:"country,omitempty"`
	Description *string             `json:"description,omitempty"`
	Email       *string             `json:"email,omitempty"`
	HomeService *bool               `json:"homeService,omitempty"`
	Kind        *string             `json:"kind,omitempty"`
	Lat         *float64            `json:"lat,omitempty"`
	Lng         *float64            `json:"lng,omitempty"`
	Logo        *openapi_types.File `json:"logo,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Phone       *string             `json:"phone,omitempty"`
	PostalCode  *string             `json:"postalCode,omitempty"`
	Region      *string             `json:"region,omitempty"`
	Website     *string             `json:"website,omitempty"`
}

// BarbershopsAppUpdateBusinessMemberInput defines model for BarbershopsAppUpdateBusinessMemberInput.
type BarbershopsAppUpdateBusinessMemberInput struct {
	Description *string             `json:"description,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Photo       *openapi_types.File `json:"photo,omitempty"`
}

// BarbershopsAppUpdatePhotoInput defines model for BarbershopsAppUpdatePhotoInput.
type BarbershopsAppUpdatePhotoInput struct {
	Alt        *string  `json:"alt,omitempty"`
	IsCarousel *bool    `json:"isCarousel,omitempty"`
	Sort       *float64 `json:"sort,omitempty"`
}

// BarbershopsAppUpdateServiceTypeInput defines model for BarbershopsAppUpdateServiceTypeInput.
type BarbershopsAppUpdateServiceTypeInput struct {
	Description *string             `json:"description,omitempty"`
	Duration    *int64              `json:"duration,omitempty"`
	Kind        *string             `json:"kind,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Photo       *openapi_types.File `json:"photo,omitempty"`
	Price       *float64            `json:"price,omitempty"`
}

// ContactServiceCareerApplication defines model for ContactServiceCareerApplication.
type ContactServiceCareerApplication struct {
	Comments  *string `json:"comments,omitempty"`
	Email     string  `json:"email"`
	Github    *string `json:"github,omitempty"`
	Id        int64   `json:"id"`
	LinkedIn  string  `json:"linkedIn"`
	Location  string  `json:"location"`
	Name      string  `json:"name"`
	Phone     *string `json:"phone,omitempty"`
	Position  string  `json:"position"`
	ResumeUrl *string `json:"resumeUrl,omitempty"`
}

// ContactServiceCareerApplicationInput defines model for ContactServiceCareerApplicationInput.
type ContactServiceCareerApplicationInput struct {
	Comments *string            `json:"comments,omitempty"`
	Email    string             `json:"email"`
	Github   *string            `json:"github,omitempty"`
	LinkedIn string             `json:"linkedIn"`
	Location string             `json:"location"`
	Name     string             `json:"name"`
	Phone    *string            `json:"phone,omitempty"`
	Position string             `json:"position"`
	Resume   openapi_types.File `json:"resume"`
}

// ContactServiceContactRequest defines model for ContactServiceContactRequest.
type ContactServiceContactRequest struct {
	Email   string  `json:"email"`
	Id      int64   `json:"id"`
	Message string  `json:"message"`
	Name    string  `json:"name"`
	Phone   *string `json:"phone,omitempty"`
	Title   string  `json:"title"`
}

// ContactServiceContactRequestInput defines model for ContactServiceContactRequestInput.
type ContactServiceContactRequestInput struct {
	Email   string  `json:"email"`
	Message string  `json:"message"`
	Name    string  `json:"name"`
	Phone   *string `json:"phone,omitempty"`
	Title   string  `json:"title"`
}

// RadminAppApp defines model for RadminAppApp.
type RadminAppApp struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description string    `json:"description"`
	Email       string    `json:"email"`
	Id          string    `json:"id"`
	IsActive    bool      `json:"isActive"`
	LogoUrl     *string   `json:"logoUrl,omitempty"`
	MainColor   string    `json:"mainColor"`
	Name        string    `json:"name"`
	UiUrl       string    `json:"uiUrl"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// RadminAppCreateAppInput defines model for RadminAppCreateAppInput.
type RadminAppCreateAppInput struct {
	Description string             `json:"description"`
	Email       string             `json:"email"`
	Id          string             `json:"id"`
	IsActive    bool               `json:"isActive"`
	Logo        openapi_types.File `json:"logo"`
	MainColor   string             `json:"mainColor"`
	Name        string             `json:"name"`
	UiUrl       string             `json:"uiUrl"`
}

// RadminAppUpdateAppInput defines model for RadminAppUpdateAppInput.
type RadminAppUpdateAppInput struct {
	Description *string             `json:"description,omitempty"`
	Email       *string             `json:"email,omitempty"`
	Id          *string             `json:"id,omitempty"`
	IsActive    *bool               `json:"isActive,omitempty"`
	Logo        *openapi_types.File `json:"logo,omitempty"`
	MainColor   *string             `json:"mainColor,omitempty"`
	Name        *string             `json:"name,omitempty"`
	UiUrl       *string             `json:"uiUrl,omitempty"`
}

// BarbershopsAppGetAdminBusinessesParams defines parameters for BarbershopsAppGetAdminBusinesses.
type BarbershopsAppGetAdminBusinessesParams struct {
	// Limit The number of items to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The starting point for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// BarbershopsAppGetBusinessesParams defines parameters for BarbershopsAppGetBusinesses.
type BarbershopsAppGetBusinessesParams struct {
	// MaxDistance The maximum distance in meters
	MaxDistance *int64 `form:"maxDistance,omitempty" json:"maxDistance,omitempty"`

	// ServiceKind The type of service
	ServiceKind *[]string `form:"serviceKind,omitempty" json:"serviceKind,omitempty"`

	// MaxPrice The maximum price to use for price search
	MaxPrice *int64 `form:"maxPrice,omitempty" json:"maxPrice,omitempty"`

	// MinPrice The minimum price to use for price search
	MinPrice *int64 `form:"minPrice,omitempty" json:"minPrice,omitempty"`

	// MinRating The minimum rating to use for rating search
	MinRating *int64 `form:"minRating,omitempty" json:"minRating,omitempty"`

	// Sort The attribute to use for sorting
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// WithinLats The latitude boundries of the search area
	WithinLats *[]float64 `form:"withinLats,omitempty" json:"withinLats,omitempty"`

	// WithinLngs The longitude boundries of the search area
	WithinLngs *[]float64 `form:"withinLngs,omitempty" json:"withinLngs,omitempty"`

	// DistanceFrom The coords from which to calculate the distance
	DistanceFrom *[]float64 `form:"distanceFrom,omitempty" json:"distanceFrom,omitempty"`

	// Search The search string
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Limit The number of items to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeNoRating Wether to include businesses with no rating
	IncludeNoRating *bool `form:"includeNoRating,omitempty" json:"includeNoRating,omitempty"`
}

// BarbershopsAppGetBusinessAvailabilityParams defines parameters for BarbershopsAppGetBusinessAvailability.
type BarbershopsAppGetBusinessAvailabilityParams struct {
	// BusinessMemberId The BusinessMember ID
	BusinessMemberId *openapi_types.UUID `form:"businessMemberId,omitempty" json:"businessMemberId,omitempty"`

	// ServiceTypeId The Service ID
	ServiceTypeId *openapi_types.UUID `form:"serviceTypeId,omitempty" json:"serviceTypeId,omitempty"`

	// Time The time
	Time *time.Time `form:"time,omitempty" json:"time,omitempty"`
}

// BarbershopsAppGetBusinessBookingsParams defines parameters for BarbershopsAppGetBusinessBookings.
type BarbershopsAppGetBusinessBookingsParams struct {
	// WeekOf A date in the week to get the data for
	WeekOf *time.Time `form:"weekOf,omitempty" json:"weekOf,omitempty"`

	// Confirmed Wether confirmedAt is not null
	Confirmed *bool `form:"confirmed,omitempty" json:"confirmed,omitempty"`
}

// BarbershopsAppCreateBusinessMemberParams defines parameters for BarbershopsAppCreateBusinessMember.
type BarbershopsAppCreateBusinessMemberParams struct {
	// Simulation Wether to persist the mutation or not, if true the mutation will not be persisted and the response will be errors if any or an empty 200
	Simulation *bool `form:"simulation,omitempty" json:"simulation,omitempty"`
}

// BarbershopsAppGetBusinessReviewsParams defines parameters for BarbershopsAppGetBusinessReviews.
type BarbershopsAppGetBusinessReviewsParams struct {
	// Limit The number of items to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The starting point for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`

	// OnlyWithText Wether to return only reviews with text
	OnlyWithText *bool `form:"onlyWithText,omitempty" json:"onlyWithText,omitempty"`
}

// BarbershopsAppCreateServiceParams defines parameters for BarbershopsAppCreateService.
type BarbershopsAppCreateServiceParams struct {
	// Simulation Wether to persist the mutation or not, if true the mutation will not be persisted and the response will be errors if any or an empty 200
	Simulation *bool `form:"simulation,omitempty" json:"simulation,omitempty"`
}

// BarbershopsAppGetMyBookingsParams defines parameters for BarbershopsAppGetMyBookings.
type BarbershopsAppGetMyBookingsParams struct {
	// Limit The number of items to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The starting point for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// BarbershopsAppGetMyReviewsParams defines parameters for BarbershopsAppGetMyReviews.
type BarbershopsAppGetMyReviewsParams struct {
	// Limit The number of items to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The starting point for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// AuthServiceGetAdminUsersParams defines parameters for AuthServiceGetAdminUsers.
type AuthServiceGetAdminUsersParams struct {
	// Limit The number of items to return
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset The starting point for pagination
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// AuthServiceGoogleSignInParams defines parameters for AuthServiceGoogleSignIn.
type AuthServiceGoogleSignInParams struct {
	// ReturnUrl The Url to return after a succesful authentication
	ReturnUrl *string `form:"returnUrl,omitempty" json:"returnUrl,omitempty"`
}

// BarbershopsAppCreateCountryJSONRequestBody defines body for BarbershopsAppCreateCountry for application/json ContentType.
type BarbershopsAppCreateCountryJSONRequestBody = BarbershopsAppCountryInput

// BarbershopsAppUpdateBusinessJSONRequestBody defines body for BarbershopsAppUpdateBusiness for application/json ContentType.
type BarbershopsAppUpdateBusinessJSONRequestBody = BarbershopsAppUpdateBusinessInput

// BarbershopsAppBookJSONRequestBody defines body for BarbershopsAppBook for application/json ContentType.
type BarbershopsAppBookJSONRequestBody = BarbershopsAppBookingInput

// BarbershopsAppSetupPaymentIntentJSONRequestBody defines body for BarbershopsAppSetupPaymentIntent for application/json ContentType.
type BarbershopsAppSetupPaymentIntentJSONRequestBody = BarbershopsAppPaymentIntentInput

// BarbershopsAppCreateReviewJSONRequestBody defines body for BarbershopsAppCreateReview for application/json ContentType.
type BarbershopsAppCreateReviewJSONRequestBody = BarbershopsAppReviewInput

// BarbershopsAppCreateBusinessMemberJSONRequestBody defines body for BarbershopsAppCreateBusinessMember for application/json ContentType.
type BarbershopsAppCreateBusinessMemberJSONRequestBody = BarbershopsAppCreateBusinessMemberInput

// BarbershopsAppUpdateBusinessMemberJSONRequestBody defines body for BarbershopsAppUpdateBusinessMember for application/json ContentType.
type BarbershopsAppUpdateBusinessMemberJSONRequestBody = BarbershopsAppUpdateBusinessMemberInput

// BarbershopsAppAddBusinessPhotoJSONRequestBody defines body for BarbershopsAppAddBusinessPhoto for application/json ContentType.
type BarbershopsAppAddBusinessPhotoJSONRequestBody = BarbershopsAppCreatePhotoInput

// BarbershopsAppUpdateBusinessPhotoJSONRequestBody defines body for BarbershopsAppUpdateBusinessPhoto for application/json ContentType.
type BarbershopsAppUpdateBusinessPhotoJSONRequestBody = BarbershopsAppUpdatePhotoInput

// BarbershopsAppUpdateBusinessScheduleJSONRequestBody defines body for BarbershopsAppUpdateBusinessSchedule for application/json ContentType.
type BarbershopsAppUpdateBusinessScheduleJSONRequestBody = BarbershopsAppBusinessScheduleInput

// BarbershopsAppCreateServiceJSONRequestBody defines body for BarbershopsAppCreateService for application/json ContentType.
type BarbershopsAppCreateServiceJSONRequestBody = BarbershopsAppCreateServiceTypeInput

// BarbershopsAppUpdateServiceJSONRequestBody defines body for BarbershopsAppUpdateService for application/json ContentType.
type BarbershopsAppUpdateServiceJSONRequestBody = BarbershopsAppUpdateServiceTypeInput

// BarbershopsAppUpdateBusinessSettingsJSONRequestBody defines body for BarbershopsAppUpdateBusinessSettings for application/json ContentType.
type BarbershopsAppUpdateBusinessSettingsJSONRequestBody = BarbershopsAppBusinessSettingsInput

// BarbershopsAppCreateBusinessJSONRequestBody defines body for BarbershopsAppCreateBusiness for application/json ContentType.
type BarbershopsAppCreateBusinessJSONRequestBody = BarbershopsAppCreateBusinessInput

// RadminAppCreateAppMultipartRequestBody defines body for RadminAppCreateApp for multipart/form-data ContentType.
type RadminAppCreateAppMultipartRequestBody = RadminAppCreateAppInput

// RadminAppUpdateAppMultipartRequestBody defines body for RadminAppUpdateApp for multipart/form-data ContentType.
type RadminAppUpdateAppMultipartRequestBody = RadminAppUpdateAppInput

// AuthServiceUpdateCurrentUserMultipartRequestBody defines body for AuthServiceUpdateCurrentUser for multipart/form-data ContentType.
type AuthServiceUpdateCurrentUserMultipartRequestBody = AuthServiceUpdateUserInput

// AuthServiceForgotPasswordJSONRequestBody defines body for AuthServiceForgotPassword for application/json ContentType.
type AuthServiceForgotPasswordJSONRequestBody = AuthServiceForgotPasswordInput

// AuthServiceResetPasswordJSONRequestBody defines body for AuthServiceResetPassword for application/json ContentType.
type AuthServiceResetPasswordJSONRequestBody = AuthServiceResetPasswordInput

// AuthServiceVerifyEmailJSONRequestBody defines body for AuthServiceVerifyEmail for application/json ContentType.
type AuthServiceVerifyEmailJSONRequestBody = AuthServiceVerifyEmailInput

// AuthServiceVerifyPhoneJSONRequestBody defines body for AuthServiceVerifyPhone for application/json ContentType.
type AuthServiceVerifyPhoneJSONRequestBody = AuthServiceVerifyPhoneInput

// AuthServiceSignInJSONRequestBody defines body for AuthServiceSignIn for application/json ContentType.
type AuthServiceSignInJSONRequestBody = AuthServiceSignInInput

// AuthServiceSignUpJSONRequestBody defines body for AuthServiceSignUp for application/json ContentType.
type AuthServiceSignUpJSONRequestBody = AuthServiceSignUpInput

// ContactServiceApplyCareerMultipartRequestBody defines body for ContactServiceApplyCareer for multipart/form-data ContentType.
type ContactServiceApplyCareerMultipartRequestBody = ContactServiceCareerApplicationInput

// ContactServiceContactRequestJSONRequestBody defines body for ContactServiceContactRequest for application/json ContentType.
type ContactServiceContactRequestJSONRequestBody = ContactServiceContactRequestInput
